ARG VERSION

FROM fedora:$VERSION

RUN useradd -ms /bin/bash user

WORKDIR /home/user

RUN echo 'user ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN mkdir test-data
COPY test-data/sat .
COPY test-data/simple.json ./test-data/simple.json

ENTRYPOINT [ "/home/user/sat" ]