ARG VERSION

FROM ubuntu:$VERSION

RUN apt-get update && apt-get install -y sudo

RUN useradd -ms /bin/bash user

WORKDIR /home/user

RUN echo 'user ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN mkdir test-data
COPY test-data .


ENTRYPOINT [ "/home/user/sat" ]